In [2]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

html = requests.get(url, headers=headers).text

sp500_table = pd.read_html(html)[0]

# Keep only relevant columns
sp500_companies = sp500_table[['Symbol', 'Security', 'GICS Sector']]

sp500_companies.head()

C:\Users\HomePC\AppData\Local\Temp\ipykernel_6508\932205190.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  sp500_table = pd.read_html(html)[0]

  Symbol             Security             GICS Sector
0    MMM                   3M             Industrials
1    AOS          A. O. Smith             Industrials
2    ABT  Abbott Laboratories             Health Care
3   ABBV               AbbVie             Health Care
4    ACN            Accenture  Information Technology

In [3]:
sp500_companies.to_csv("sp500_companies.csv", index=False)

In [4]:
sector_df = pd.read_csv("sp500_companies.csv")
sector_df.head()

  Symbol             Security             GICS Sector
0    MMM                   3M             Industrials
1    AOS          A. O. Smith             Industrials
2    ABT  Abbott Laboratories             Health Care
3   ABBV               AbbVie             Health Care
4    ACN            Accenture  Information Technology

In [5]:
sector_df = sector_df[['Security', 'GICS Sector']]

sector_df.rename(columns={
    'Security': 'Company_CSR',
    'GICS Sector': 'Sector'
}, inplace=True)

sector_df['Company_CSR'] = sector_df['Company_CSR'].str.lower().str.strip()